do

--[[
InsimExtractor -- turns the `mission` table inside a .miz into fixture templates.

Runs OUTSIDE DCS, on the same stock Lua 5.1 that test/lua uses. It never touches the DCS API,
which is what makes it unit-testable.

Templates are position-independent: unit types, headings, skills and offsets from the group's
first unit. Absolute coordinates live in fixtures/placements.lua instead, so a composition can
be re-anchored anywhere. Offsets are mission-table (Vec2) values: dx is NORTH, dy is EAST.

Usage:
  unzip -o mission.miz mission          -- by hand; see test/insim/README.md
  lua5.1 extract-fixtures.lua mission SAM-Kub > fixtures/generated/sam-kub.lua
]]

InsimExtractor = {}

--- One group table -> a position-independent template.
function InsimExtractor.templateFromGroup(group)
  assert(type(group) == "table", "templateFromGroup: group must be a table")
  assert(type(group.units) == "table" and group.units[1],
    "templateFromGroup: group '" .. tostring(group.name) .. "' has no units")

  local origin = group.units[1]
  local template = { name = group.name, task = group.task, units = {} }

  for i, unit in ipairs(group.units) do
    template.units[i] = {
      type = unit.type,
      dx = unit.x - origin.x,
      dy = unit.y - origin.y,
      heading = unit.heading,
      skill = unit.skill,
    }
  end

  return template
end

--- One static group table -> a template. Statics are a single unit carrying a category.
function InsimExtractor.templateFromStatic(staticGroup)
  assert(type(staticGroup) == "table", "templateFromStatic: argument must be a table")
  local unit = staticGroup.units and staticGroup.units[1]
  assert(unit, "templateFromStatic: '" .. tostring(staticGroup.name) .. "' has no unit")
  return {
    name = staticGroup.name,
    type = unit.type,
    category = unit.category,
    heading = unit.heading,
  }
end

--- Every vehicle/static group whose name starts with `prefix`, in any coalition or country.
function InsimExtractor.groupsFromMissionTable(mission, prefix)
  assert(type(mission) == "table", "groupsFromMissionTable: mission must be a table")
  assert(type(prefix) == "string", "groupsFromMissionTable: prefix must be a string")

  local found = {}
  local coalitions = mission.coalition or {}

  for _, coalition in pairs(coalitions) do
    for _, country in pairs(coalition.country or {}) do
      for _, category in pairs({ country.vehicle, country.static }) do
        for _, group in pairs((category or {}).group or {}) do
          if type(group.name) == "string" and group.name:sub(1, #prefix) == prefix then
            found[#found + 1] = group
          end
        end
      end
    end
  end

  table.sort(found, function(a, b) return a.name < b.name end)
  return found
end

--- Distinguishes a static group from a vehicle group. Mission files mark statics by carrying a
--- `category` on the unit ("Armor", "Fortifications", ...); vehicle and aircraft units never
--- do. Measured across two independent missions in this project: 156 static units carry
--- `category`, zero vehicle or plane units do.
function InsimExtractor.isStaticGroup(group)
  local unit = type(group) == "table" and group.units and group.units[1]
  return unit ~= nil and unit.category ~= nil
end

--- A committed fixture file: a Lua chunk returning { <key> = <template>, ... }.
function InsimExtractor.fixtureFileText(templatesByName)
  local lines = {
    "--- GENERATED by test/insim/tools/extract-fixtures.lua -- do not edit by hand.",
    "--- Offsets are mission-table (Vec2): dx is NORTH, dy is EAST.",
    "return " .. InsimTestTools.serialize(templatesByName),
    "",
  }
  return table.concat(lines, "\n")
end

end

--- Command-line entry point. Silent when dofile'd by a test (arg is nil then).
if arg and arg[0] and arg[0]:find("extract%-fixtures") and arg[1] then
  local missionPath, prefix = arg[1], arg[2]
  assert(prefix, "usage: lua5.1 extract-fixtures.lua <mission-file> <group-name-prefix>")

  local base = debug.getinfo(1, "S").source:match("^@(.+)[\\/]") or "."
  dofile(base .. "/insim-test-tools.lua")

  local chunk = assert(loadfile(missionPath))
  -- A .miz's `mission` file is a Lua chunk assigning the global `mission`.
  chunk()
  assert(type(mission) == "table", "no global `mission` table after loading " .. missionPath)

  local templates = {}
  for _, group in ipairs(InsimExtractor.groupsFromMissionTable(mission, prefix)) do
    local isStatic = InsimExtractor.isStaticGroup(group)
    templates[group.name] = isStatic
      and InsimExtractor.templateFromStatic(group)
      or InsimExtractor.templateFromGroup(group)
  end

  io.write(InsimExtractor.fixtureFileText(templates))
end
