do

--[[
InsimReport -- one result set, three outputs.

  * on screen via trigger.action.outText -- the primary readout, so a tester never alt-tabs
  * dcs.log via env.info, tagged SKYNET_INSIM -- failure detail and context
  * test/insim/results/last-run.lua -- machine-readable, gitignored

No reader for the results file is built: the file is the contract that makes one trivial later.
]]

InsimReport = {}

local TAG = "SKYNET_INSIM"
local SCREEN_SECONDS = 30

function InsimReport.summaryText(results)
  local lines = { string.format("Skynet insim: %d passed, %d failed",
    results.passed, results.failed) }

  if results.failed == 0 then
    lines[#lines + 1] = "ALL PASSED"
    return table.concat(lines, "\n")
  end

  for _, suite in ipairs(results.suites or {}) do
    for _, test in ipairs(suite.tests or {}) do
      if test.status == "fail" then
        lines[#lines + 1] = string.format("  FAIL %s.%s", suite.name, test.name)
      end
    end
  end

  return table.concat(lines, "\n")
end

function InsimReport.detailLines(results)
  local lines = { string.format("%s: %d passed, %d failed",
    TAG, results.passed, results.failed) }

  for _, suite in ipairs(results.suites or {}) do
    for _, test in ipairs(suite.tests or {}) do
      lines[#lines + 1] = string.format("%s: %s %s.%s",
        TAG, test.status == "pass" and "PASS" or "FAIL", suite.name, test.name)
      if test.message then
        lines[#lines + 1] = string.format("%s:   %s", TAG, test.message)
      end
    end
  end

  return lines
end

function InsimReport.resultsFileText(results)
  return "--- GENERATED by test/insim. Overwritten on every run.\nreturn "
    .. InsimTestTools.serialize(results) .. "\n"
end

--- Writes all three. `repoPath` nil (or io unavailable) skips the file and still reports.
function InsimReport.emit(results, repoPath)
  trigger.action.outText(InsimReport.summaryText(results), SCREEN_SECONDS)

  for _, line in ipairs(InsimReport.detailLines(results)) do
    env.info(line)
  end

  if not repoPath or not io then
    return
  end

  local path = repoPath .. "/test/insim/results/last-run.lua"
  local handle, err = io.open(path, "w")
  if not handle then
    env.info(string.format("%s: cannot write %s (%s)", TAG, path, tostring(err)))
    return
  end
  handle:write(InsimReport.resultsFileText(results))
  handle:close()
end

end
